#!/bin/sh
echo "apt-get 快速执行工具 V1.0 (移除依赖)- by WindFox OPO"
echo "此程序应在用apt-get或am删除程序后执行。"
echo "如果您不是root用户，会要求您输入密码，这是正常的，我们不会窃取您的任何信息。"
echo "为确保数据安全，仍会询问您需不需要移除(Y/n)，请自行斟酌。"
sudo apt autoremove
echo "感谢您的使用！"
